version: '2'

# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: password
# ADVANCED OPTIONS; Database host: postgres-container

services:
  drupal-container:
    build:
      context: .
    ports:
      - 8081:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgres-container:
    image: postgres:9.6.9
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    restart: always

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  postgres-data: